### ISSUE TITLE
[1437395864] WARNING: [broker-master] Error on socket shutdown: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by opsidevzi** [naparuba/shinken#1684]
Our old Shinken cluster was running 2.0.2 and had a lot of issues where the arbiter died and/or livestatus stopped working.
This issue resulted in us getting this message in the Thruk web interface

> backend 2: ERROR: failed to connect - Connection refused (localhost:50000)

and this message in the /tmp/ls.debug log

>[1437396285] Error :   [Livestatus Query] Error: 'Hosts' object has no attribute '__itersorted__'
>Traceback (most recent call last):
>  File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 318, in launch_query
>    result = self.get_live_data(cs)
>  File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 583, in get_live_data
>    result = handler(self, cs)
>  File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 403, in get_hosts_livedata
>    return self.get_hosts_or_services_livedata(cs)
>  File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 390, in >get_hosts_or_services_livedata
>    items = getattr(self.datamgr.rg, self.table).__itersorted__(self.metainfo.query_hints)
> AttributeError: 'Hosts' object has no attribute '__itersorted__'

Since we were pretty far behind the current version we decided to build a new cluster from scratch. The new cluster would be deployed as a replica of the old one.

##### Cluster overview.
We are monitoring around 4000 hosts and over 25000 services.
This is what our previous cluster looked like

* Master
  * arbiter
  * broker
  * receiver
  * reactioner
  * Thruk
* 8 Pollers
* 1 Scheduler

When i installed the machines i used the latest git snapshot of 2.4 on all of them.

##### Issue: Error on socket shutdown: [Errno 9] Bad file descriptor

After installing the Master, a Poller and the Scheduler i verified that it was working by running check_icmp against 184 hosts, this gave no issues at all.
The issue occurred when i added the last 7 Poller's.

After a very short while i got the same error message in Thruk as with our old cluster.
I also noticed that livestatus kept dying and re-spawning with a different PID.
As it worked with one Poller i started to add them in pairs with one as the primary and the other one as a spare.

Removed all Poller's except 2 and 3, with 3 acting as a spare.
* Issued 100 checks (check_icmp) to reproduce the issue: Not possible to reproduce
* Issued 184 checks (check_icmp) to reproduce the issue: Not possible to reproduce.

Added Poller 4 and 5, with 5 acting as a spare.
* Issued 100 checks (check_icmp) to reproduce the issue: Not possible to reproduce
* Issued 184 checks (check_icmp) to reproduce the issue: Not possible to reproduce.

Added Poller 6 and 7, with 7 acting as a spare.
* Issued 100 checks (check_icmp) to reproduce the issue: Not possible to reproduce.
* Issued 184 checks (check_icmp) to reproduce the issue: Not possible to reproduce.
* Issued 184 checks (check_icmp) two times in rapid succession to reproduce the issue: Not possible to reproduce.

Added Poller 8 and 9, with 9 as a spare.
* Issued 100 checks (check_icmp) to reproduce the issue: Issue is reproduced. 

I also attempted setting up a spare of the Master, with the same results of course

With Shinken 2.4 it looks like we are unable to run more than three primary Poller's and i'm guessing that this isn't due to any new limitations to Shinken. 

Is this caused by a configuration error? If so, what?
Is this an issue that's addressed in 2.4.1? (no changelog for 2.4.1?)
I've spent too much time troubleshooting this issue and might have gone a bit "blind", do you have any other suggestion on how to troubleshoot this further?

Please let me know if you need more information, i'm sure that i've forgot something :)

**Comment by opsidevzi** [comment]
Here's an example of how often the issue occurs

> Time: 15:50:43 - PID: 1045 --- Livestatus failures: 1 
> Time: 15:53:41 - PID: 2126 --- Livestatus failures: 2 
> Time: 15:54:54 - PID: 2646 --- Livestatus failures: 3 
> Time: 15:56:56 - PID: 3489 --- Livestatus failures: 4 
> Time: 15:58:21 - PID: 4023 --- Livestatus failures: 5 
> Time: 15:59:46 - PID: 4544 --- Livestatus failures: 6 
> Time: 16:00:57 - PID: 4999 --- Livestatus failures: 7 
> Time: 16:03:58 - PID: 6097 --- Livestatus failures: 8

**Comment by Pi3R1k** [comment]
I confirm this problem on shinken 2.4.0  and 2.4.1 with similar architecture : 
1500 hosts and 15000 services.

- Master
    - arbiter
    - broker
    - receiver
    - reactioner
    - Thruk
- 4 Pollers


Livestatus crash randomly in my case and the error message is the same : 
** WARNING: [broker] Error on socket shutdown: [Errno 9] Bad file descriptor**

After a while, it  again become available for a randomly time.

**Comment by Bifrozt** [comment]
"Glad" to see i'm not alone with having this issue with 2.4.0. My setup is identical to @Pi3R1k but far less hosts and services.
It should be mentioned that it might be solved by splitting the pollers into separate realms, 3 in each, with their own schedulers.
Not sure if this is the correct way to do its been running for an hour-ish without issues now.
Is this some sort of new limitation or something?

**Comment by olivierHa** [comment]
Hello,

Which version of livestatus are you all using ?

Could you give a try with this version :

https://github.com/shinken-monitoring/mod-livestatus/commit/b9f2883e5f834e39634e02dca5d0bee69effc3b9

Olivier

"Glad" to see i'm not alone with having this issue with 2.4.0. My setup is
identical to @Pi3R1k <https://github.com/Pi3R1k> but far less hosts and
services.
It should be mentioned that it might be solved by splitting the pollers
into separate realms, 3 in each, with their own schedulers.
Not sure if this is the correct way to do its been running for an hour-ish
without issues now.
Is this some sort of new limitation or something?

—
Reply to this email directly or view it on GitHub
<https://github.com/naparuba/shinken/issues/1684#issuecomment-123406862>.

**Comment by opsidevzi** [comment]
We are using livestatus 1.4.2

>{
>  "name": "livestatus",
>  "types": ["module"],
>  "version": "1.4.2",
>  "homepage": "http://github.com/shinken-monitoring/mod-livestatus",
>  "author": "Jean Gabès",
>  "description": "Livestatus module for Shinken",
>  "contributors": [
>    {
>      "name": "Jean Gabès",
>      "email": "naparuba@gmail.com"
>    },
>    {
>      "name": "Grégory Starck",
>      "email": "g.starck@gmail.com"
>    }
>  ],
>  "repository": "https://github.com/shinken-monitoring/mod-livestatus",
>  "keywords": [
>    "mod-livestatus",
>    "module",
>    "broker",
>    "livestatus",
>    "LQL"
>  ],
>  "dependencies": {
>    "shinken": ">=2.4"
>  },
>  "license": "AGPL"
>}

**Comment by Bifrozt** [comment]
Same here, 1.4.2

**Comment by ryltenius** [comment]
Same issue here, shinken 2.4 and thruk 2.0 livestatus. 1.4.2

**Comment by opsidevzi** [comment]
Although its a strange one, it looks like we solved it by separating the pollers into different realms.
* poller 2 - 7 in the default realm (All)
* poller 8 also working scheduler for the second realm (NewRealm)
* poller 9 in the second realm

##### Why is this the solution?
##### Why do we have to do it this way in 2.4 and not in the previous versions?

**Comment by Bifrozt** [comment]
Any other suggestions?

**Comment by ryltenius** [comment]
Would love some input here :)

**Comment by olivierHa** [comment]
Did you try an older version of the livestatus module ? 

https://github.com/shinken-monitoring/mod-livestatus/commit/b9f2883e5f834e39634e02dca5d0bee69effc3b9

**Comment by opsidevzi** [comment]
We tried different livestatus versions on our old cluster as well as this one, same results on both.

**Comment by olivierHa** [comment]
ping @naparuba

**Comment by Bifrozt** [comment]
Have anyone managed to solve this yet?

**Comment by opsidevzi** [comment]
Don't appears so :(
Any suggested workarounds for this issue?

**Comment by ryltenius** [comment]
Haven't found any workaround either:(

Hälsningar/Regards

Axel Ryltenius

**Comment by fullmetalucard** [comment]
Any feedback ? Same Problem here. Problem appears randomly in 2.4, 2.4.1, or even installed directly from the master branch. This is very annoying, migration in 2.4 is actually compromised even if the duplicate service problem (#1705) has been fixed.

Our livestatus is completly unstable..

Here is an extract of what we can see in ls.debug file:
```
[1441376508] DEBUG: [broker-1] [Logstore SQLite] commit.....
[1441376511] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441376511] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441376511] DEBUG: [broker-1] [Livestatus Log Lines] Does not match

AttributeError: 'Services' object has no attribute '__itersorted__'
Traceback (most recent call last):
  File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 346, in launch_query
    result = self.get_live_data(cs)
  File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 582, in get_live_data
    result = handler(self, cs)
  File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 411, in get_filtered_livedata
    items = getattr(self.datamgr.rg, self.table).__itersorted__(self.metainfo.query_hints)
AttributeError: 'Hostgroups' object has no attribute '__itersorted__'
Traceback (most recent call last):
  File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 346, in launch_query
/exiting now
...skipping
[1441376475] WARNING: [broker-1] Error on socket shutdown: [Errno 9] Bad file descriptor
[1441376475] WARNING: [broker-1] Error on socket shutdown: [Errno 9] Bad file descriptor
[1441376475] INFO: [broker-1] [livestatus]: exiting now..
```
Regards,

**Comment by geektophe** [comment]
Could you have a test with a single poller and tell us if the problem remains ? This is just to see if there's really a link with the number of pollers.

I would be a bit surprised if it were related to this as there is no direct connection between a broker module and the pollers.

Does it happen at any random moment, or after an arbiter or scheduler restart ?

Another question, does only the livestatus module crash, or does the whole broker service die with him ?

**Comment by fullmetalucard** [comment]
In our case, we allready tried to  disonnect extra pollers and realms, to see what happens with only one poller on the master server and the problem remained.
The problem does not appear especially after restart/reload of the arbiter. It's totally in a random mode.
When migrating to 2.4, we encountered this problem at the very beginning an then it disappeared for a while. We thought it was gone and then it happened again and now very often. Between those two periods we didn't change any module/component of the master configuration but we only added extra pollers and connected a few realms also.
As i said before, disconnecting all the extra servers didn't solved the issue as we thought it might be related to as we tried to come back to a stable state with the master server.
So for now we even reinstalled completly the master with 2.4.1 version and all the modules. Our impression is that when livestatus commits changes to livelogs.db through the logstore-sqlite module (in our case) something wrong happens but we don't know what.
To answer your last question, only the livestatus crashes, the broker remains and restart livestatus until the next crash.

Our configuration: 
- Shinken 2.4.1 + patch from #1705 issue
- modules (latest versions installed via shinken install):  livestatus, logstore-sqlite,picke-retention-file-scheduler
- Thruk 2.0
- about 6000 services /600 hosts managed by the master (worked well with this configuration in 1.4 version)

Regards

**Comment by geektophe** [comment]
A problem with the logstore_sqlite module seems a more promising track.

I have a test cluster under 2.4.1 version, with Livestatus version 1.4.2, and a bigger configuration. I'm using a logstore_mongodb logs backend, and I didn't face this issue.

To see if it's really related to it, could you have a test with logstore_null or logstore_mongodb module, rather than logstore_sqlite ?

On my own, I'll have a test with logstore_sqlite to see if I can reproduce the issue.

What distribution are you using ?

**Comment by ryltenius** [comment]
We use debian

//
Axel

**Comment by fullmetalucard** [comment]
Hi,

We also use debian (Jessie 8.2 / PPC architecture) on the master server, and 4 pollers ( 2 installed on amd64 arch et 2 others on a ppc arch/ all are debian 8)  which I agree is quite experimental.
The fact is that the master crashes even if the pollers from other archs are disconnected.

About logstore-sqlite, we also tried with logstore-null, but we  stille have the problem. We cannot test it with logstore-mongodb because there's no package of mongo on PPC architecture. And as logstore-null doesn't work and solve the case, my guess is that if this module doesn't succeed, logstore-mongodb won't do better. But anyway  we are going to try it try to install it on a amd64 deported machine, we must find a way to make it work again, because it did!

**Comment by fullmetalucard** [comment]
I forgot to mention that we replaced logsore-sqlite in the livestatus configuration but the it was still mentioned in the logs.
So we tried to remove completley /var/lib/shinken/modules/logstore-sqlite, and shinken complained about the fact it was missing although we completely removed it from the config files...very strange.

We also noticed something about the "crash process":
The broker stops the livestatus:

```
[1441383598] DEBUG: [broker-1] Begin Loop: managing old broks (0)
[1441383598] DEBUG: [broker-1] External Queue len (livestatus): 0
[1441383598] DEBUG: [broker-1] External Queue len (npcdmod): 0
[1441383598] DEBUG: [broker-1] Ask stop process for livestatus
[1441383598] INFO: [broker-1] I'm stopping module u'livestatus' (pid=9371)
[1441383598] INFO: [broker-1] [Livestatus Broker] So I quit
[1441383598] INFO: [broker-1] [Livestatus Broker] So I quit
[1441383598] WARNING: [broker-1] Error on socket shutdown: [Errno 9] Bad file descriptor
[1441383598] WARNING: [broker-1] Error on socket shutdown: [Errno 9] Bad file descriptor
[1441383598] INFO: [broker-1] [livestatus]: exiting now..
[1441383599] DEBUG: [broker-1] Stop process done
[1441383599] DEBUG: [broker-1] Ask stop process for npcdmod
[1441383599] INFO: [broker-1] I'm stopping module u'npcdmod' (pid=9398)
[1441383600] WARNING: [broker-1] u'npcdmod' is still alive normal kill, I help it to die
[1441383601] DEBUG: [broker-1] Debug perf: push_broks [args:0.00163602828979] [aqu_lock:9.53674316406e-07][calling:2.90870666504e-05] [json:3.79085540771e-05] [global:0.00170397758484]
[1441383601] DEBUG: [broker-1] Stop process done
[1441383601] INFO: [broker-1] Waiting for initial configuration
```

Just before that in brokerd.log we can observe: (as you can read we see our friend logstore-sqlite which in theory has been removed..)

```
[1441383593] DEBUG: [broker-1] Begin Loop: managing old broks (0)
[1441383593] DEBUG: [broker-1] External Queue len (livestatus): 0
[1441383593] DEBUG: [broker-1] External Queue len (npcdmod): 0
[1441383594] DEBUG: [broker-1] [broker-1] New running id for the scheduler scheduler-1: 1441383464.87 (was 0)
[1441383594] DEBUG: [broker-1] [broker-1] I ask for a broks generation to the scheduler scheduler-1
[1441383594] DEBUG: [broker-1] HTTP: calling lock for wait_new_conf
[1441383595] DEBUG: [broker-1] [Logstore SQLite] commit.....
[1441383597] INFO: [broker-1] Connection OK to the scheduler scheduler-1
[1441383597] DEBUG: [broker-1] 1 Broks get in 0.0022349357605
[1441383597] DEBUG: [broker-1] 1 Broks get in 0.00188899040222
[1441383597] DEBUG: [broker-1] 1 Broks get in 0.00298690795898
[1441383597] DEBUG: [broker-1] 1 Broks get in 0.0015881061554
[1441383597] DEBUG: [broker-1] 0 Broks get in 0.00159406661987
[1441383597] DEBUG: [broker-1] Time to send 4 broks (0 secs)
[1441383597] DEBUG: [broker-1] Arbiter wants me to wait for a new configuration
[1441383597] DEBUG: [broker-1] Debug perf: wait_new_conf [args:1.09672546387e-05] [aqu_lock:2.67080688477][calling:0.000290155410767] [json:3.00407409668e-05] [global:2.67113804817]
[1441383597] DEBUG: [broker-1] Debug perf: ping [args:3.09944152832e-06] [aqu_lock:9.53674316406e-07][calling:1.90734863281e-06] [json:5.00679016113e-06] [global:1.09672546387e-05]
[1441383597] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441383597] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441383597] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441383597] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441383598] DEBUG: [broker-1] Begin Loop: managing old broks (0)
[1441383598] DEBUG: [broker-1] External Queue len (livestatus): 0
[1441383598] DEBUG: [broker-1] External Queue len (npcdmod): 0
[1441383598] DEBUG: [broker-1] Ask stop process for livestatus
[1441383598] INFO: [broker-1] I'm stopping module u'livestatus' (pid=9371)
[1441383598] INFO: [broker-1] [Livestatus Broker] So I quit
[1441383598] INFO: [broker-1] [Livestatus Broker] So I quit
[1441383598] WARNING: [broker-1] Error on socket shutdown: [Errno 9] Bad file descriptor
[1441383598] WARNING: [broker-1] Error on socket shutdown: [Errno 9] Bad file descriptor
[1441383598] INFO: [broker-1] [livestatus]: exiting now..
--
[1441383983] DEBUG: [broker-1] Debug perf: what_i_managed [args:5.00679016113e-06] [aqu_lock:9.53674316406e-07][calling:0.000189065933228] [json:3.00407409668e-05] [global:0.000225067138672]
[1441383983] DEBUG: [broker-1] [Logstore SQLite] commit.....
[1441383985] DEBUG: [broker-1] 3 Broks get in 14.7448210716
[1441383985] DEBUG: [broker-1] 1 Broks get in 0.00344800949097
[1441383985] DEBUG: [broker-1] HTTP: calling lock for wait_new_conf
[1441383985] DEBUG: [broker-1] 1 Broks get in 0.00229406356812
[1441383985] DEBUG: [broker-1] 0 Broks get in 0.00143790245056
[1441383985] DEBUG: [broker-1] Time to send 5 broks (0 secs)
[1441383985] DEBUG: [broker-1] Arbiter wants me to wait for a new configuration
[1441383985] DEBUG: [broker-1] Debug perf: wait_new_conf [args:9.05990600586e-06] [aqu_lock:6.94074201584][calling:0.000144958496094] [json:2.78949737549e-05] [global:6.94092392921]
[1441383985] DEBUG: [broker-1] Arbiter wants me to wait for a new configuration
[1441383985] DEBUG: [broker-1] Debug perf: wait_new_conf [args:6.91413879395e-06] [aqu_lock:0.00573396682739][calling:0.000153064727783] [json:1.59740447998e-05] [global:0.00590991973877]
[1441383985] DEBUG: [broker-1] Debug perf: ping [args:5.00679016113e-06] [aqu_lock:9.53674316406e-07][calling:1.90734863281e-06] [json:9.05990600586e-06] [global:1.69277191162e-05]
[1441383985] DEBUG: [broker-1] Debug perf: push_broks [args:0.0388181209564] [aqu_lock:9.53674316406e-07][calling:1.90734863281e-05] [json:1.78813934326e-05] [global:0.0388560295105]
[1441383985] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441383985] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441383985] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441383985] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441383985] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441383985] DEBUG: [broker-1] Debug perf: ping [args:5.00679016113e-06] [aqu_lock:9.53674316406e-07][calling:9.53674316406e-07] [json:9.05990600586e-06] [global:1.59740447998e-05]
[1441383985] DEBUG: [broker-1] Debug perf: get_external_commands [args:5.00679016113e-06] [aqu_lock:9.53674316406e-07][calling:2.00271606445e-05] [json:8.10623168945e-06] [global:3.40938568115e-05]
[1441383986] DEBUG: [broker-1] Begin Loop: managing old broks (0)
[1441383986] DEBUG: [broker-1] External Queue len (livestatus): 0
[1441383986] DEBUG: [broker-1] External Queue len (npcdmod): 0
[1441383986] DEBUG: [broker-1] Ask stop process for livestatus
[1441383986] INFO: [broker-1] I'm stopping module u'livestatus' (pid=13066)
[1441383986] INFO: [broker-1] [Livestatus Broker] So I quit
[1441383986] INFO: [broker-1] [Livestatus Broker] So I quit
[1441383986] WARNING: [broker-1] Error on socket shutdown: [Errno 9] Bad file descriptor
[1441383986] WARNING: [broker-1] Error on socket shutdown: [Errno 9] Bad file descriptor
[1441383986] INFO: [broker-1] [livestatus]: exiting now..
--
[1441386472] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441386472] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441386472] DEBUG: [broker-1] [Livestatus Log Lines] Does not match
[1441386473] DEBUG: [broker-1] Begin Loop: managing old broks (0)
[1441386473] DEBUG: [broker-1] External Queue len (livestatus): 0
[1441386473] DEBUG: [broker-1] External Queue len (npcdmod): 0
[1441386473] DEBUG: [broker-1] [Logstore SQLite] commit.....
[1441386473] INFO: [broker-1] Connection OK to the scheduler scheduler-1
[1441386473] DEBUG: [broker-1] 0 Broks get in 0.0290818214417
[1441386473] DEBUG: [broker-1] 0 Broks get in 0.26312494278
[1441386473] DEBUG: [broker-1] HTTP: calling lock for wait_new_conf
[1441386473] DEBUG: [broker-1] 0 Broks get in 0.00373506546021
[1441386473] DEBUG: [broker-1] 0 Broks get in 0.00101804733276
[1441386473] DEBUG: [broker-1] 0 Broks get in 0.00098705291748
[1441386473] DEBUG: [broker-1] Time to send 0 broks (0 secs)
[1441386473] DEBUG: [broker-1] Arbiter wants me to wait for a new configuration
[1441386473] DEBUG: [broker-1] Debug perf: wait_new_conf [args:5.96046447754e-06] [aqu_lock:0.00368499755859][calling:0.00020694732666] [json:2.21729278564e-05] [global:0.00392007827759]
[1441386473] DEBUG: [broker-1] Debug perf: ping [args:3.09944152832e-06] [aqu_lock:0.0][calling:1.90734863281e-06] [json:5.00679016113e-06] [global:1.00135803223e-05]
[1441386473] DEBUG: [broker-1] Debug perf: push_broks [args:0.000770092010498] [aqu_lock:9.53674316406e-07][calling:1.09672546387e-05] [json:1.00135803223e-05] [global:0.000792026519775]
[1441386473] DEBUG: [broker-1] Debug perf: ping [args:8.10623168945e-06] [aqu_lock:1.90734863281e-06][calling:3.09944152832e-06] [json:2.00271606445e-05] [global:3.31401824951e-05]
[1441386473] DEBUG: [broker-1] Debug perf: get_external_commands [args:5.00679016113e-06] [aqu_lock:9.53674316406e-07][calling:2.69412994385e-05] [json:9.05990600586e-06] [global:4.19616699219e-05]
[1441386474] DEBUG: [broker-1] Begin Loop: managing old broks (0)
[1441386474] DEBUG: [broker-1] External Queue len (livestatus): 0
[1441386474] DEBUG: [broker-1] External Queue len (npcdmod): 0
[1441386474] DEBUG: [broker-1] Ask stop process for livestatus
[1441386474] INFO: [broker-1] I'm stopping module u'livestatus' (pid=7200)
[1441386474] INFO: [broker-1] [Livestatus Broker] So I quit
[1441386475] INFO: [broker-1] [Livestatus Broker] So I quit
[1441386475] WARNING: [broker-1] Error on socket shutdown: [Errno 9] Bad file descriptor
[1441386475] WARNING: [broker-1] Error on socket shutdown: [Errno 9] Bad file descriptor
[1441386475] INFO: [broker-1] [livestatus]: exiting now..
```


We also noticed we had  a lot of timeout connection between the daemons, so we change from 3 to 10 second (didn't change anything):

[1441490468] WARNING: [Shinken] Add failed attempt to scheduler-1 (1/3) Connection error to http://X.X.X.X:7768/ : Operation timed out after 3001 milliseconds with 0 bytes received
[1441490528] WARNING: [Shinken] Add failed attempt to scheduler-1 (2/3) Connection error to http://X.X.X.X:7768/ : Operation timed out after 3001 milliseconds with 0 bytes received
[1441490534] ERROR: [Shinken] Failed sending configuration for scheduler-1: Connection error to http://X.X.X.X:7768/ : Operation timed out after 3000 milliseconds with 0 bytes received

**Comment by jthoe** [comment]
On our side, the problem was:
* timeout between the arbiter and the scheduler
* then the arbiter was redispatching the configuration
* then when receiving the new configuration the broker was killing its module and restarting them

The timeouts where due to not enough thread on the scheduler. We had to increase the number of thread as said there: https://groups.google.com/forum/#!topic/shinken-devel/Xzn-fUQ3DTU

As well this patch need to be applied (normally already present in 2.4.1):
 Fix: Debian 8/pycurl dead lock on POST, now use a socket for each act…
    https://github.com/naparuba/shinken/commit/e8d929c5aa8fb0e9e8b524919997715640335485


The error "Error on socket shutdown: [Errno 9] Bad file descriptor" happens during the restart of the module of the broker after the arbiter has redispatched the config after having timeout towards the scheduler, this is not really an error juste a warning during the restart of the modules: 
<pre>
[1441386473] DEBUG: [broker-1] Arbiter wants me to wait for a new configuration
[1441386474] DEBUG: [broker-1] Ask stop process for livestatus
[1441386474] INFO: [broker-1] I'm stopping module u'livestatus' (pid=7200)
[1441386474] INFO: [broker-1] [Livestatus Broker] So I quit
[1441386475] INFO: [broker-1] [Livestatus Broker] So I quit
[1441386475] WARNING: [broker-1] Error on socket shutdown: [Errno 9] Bad file descriptor
[1441386475] WARNING: [broker-1] Error on socket shutdown: [Errno 9] Bad file descriptor
[1441386475] INFO: [broker-1] [livestatus]: exiting now..

</pre>

**Comment by fullmetalucard** [comment]
Hi, @jthoe is right, we fixed the problem by adding something like in schedulerd.ini:
```
daemon_thread_pool_size=50
```

As the arbiter used to have timeouts with the scheduler, he always sent the config back again and again to the broker which reloaded livestatus again and again. Our platform is now stable with that configuration.
@opsidevzi : could you test this configuration and see if that fixes your problem?

**Comment by geektophe** [comment]
Great news :)

**Comment by olivierHa** [comment]
I am closing it.
Please feel free to reopen it if you encounter again this issue
