### ISSUE TITLE
Scheduler crash at launch : 'NotificationWay' object has no attribute 'service_notification_commands'

### ISSUE THREAD

**Issue by vinzwog** [naparuba/shinken#1210]
Hello,

We have a Shinken 1.4 in production and i'm testing update in version 2 and i'm facing a weird issue :
I installed a fresh Shinken 2.0.2 on a *VIRTUAL* tesing environment (RedHat 6.4). I have copied my old 1.4 configuration without modification and evithing worked (check, start, stop, reload). Very happy because of the simplicity and the quickness of the process, i wrote a protocole and begin to validate it on *PHYSICAL* testing server (Same master of RedHat 6.4). All the steps were exactly the same, command for command, and after shinken had started, the scheduler crash ! :-(

I've got this message at the end of the scheduler.log :
```
014-06-06 13:41:42,580 [1402054902] Critical : I got an unrecoverable error. I have to exit
2014-06-06 13:41:42,580 [1402054902] Critical : You can log a bug ticket at https://github.com/naparuba/shinken/issues/new to get help
2014-06-06 13:41:42,582 [1402054902] Critical : Back trace of it: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Shinken-2.0.2-py2.6.egg/shinken/daemons/schedulerdaemon.py", line 479, in main
    self.do_mainloop()
  File "/usr/lib/python2.6/site-packages/Shinken-2.0.2-py2.6.egg/shinken/daemon.py", line 322, in do_mainloop
    self.do_loop_turn()
  File "/usr/lib/python2.6/site-packages/Shinken-2.0.2-py2.6.egg/shinken/daemons/schedulerdaemon.py", line 333, in do_loop_turn
    self.sched.run()
  File "/usr/lib/python2.6/site-packages/Shinken-2.0.2-py2.6.egg/shinken/scheduler.py", line 1522, in run
    f()
  File "/usr/lib/python2.6/site-packages/Shinken-2.0.2-py2.6.egg/shinken/scheduler.py", line 538, in scatter_master_notifications
    childnotifications = item.scatter_notification(a)
  File "/usr/lib/python2.6/site-packages/Shinken-2.0.2-py2.6.egg/shinken/objects/schedulingitem.py", line 1250, in scatter_notification
    notif_commands = contact.get_notification_commands(cls.my_type)
  File "/usr/lib/python2.6/site-packages/Shinken-2.0.2-py2.6.egg/shinken/objects/contact.py", line 159, in get_notification_commands
    r.extend(getattr(nw, notif_commands_prop))
AttributeError: 'NotificationWay' object has no attribute 'service_notification_commands'
```
- I checked contacts, contacgroups and notificationways ... Everything seems to be ok, it worked on 1.4 and configuration check is ok
- I tried to remove ALL my old 1.4 config and replace the origin fresh install configuration, and i have got the very same problem !

I really hope i've just done a stupid mistake but except platform type difference (Virtual and Physical) i don't see anything ...

Any clue will be greatly enjoyed !

**Comment by Seb-Solon** [comment]
Please try again in next release. I think it's fixed. Open a new ticket if necessary
